//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetitTournant.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringLocalisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLocalisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetitTournant.Localisation.StringLocalisation", typeof(StringLocalisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Cookbooks.
        /// </summary>
        public static string BookSelector {
            get {
                return ResourceManager.GetString("BookSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Cookbook.
        /// </summary>
        public static string CreateCookBook {
            get {
                return ResourceManager.GetString("CreateCookBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit selected Cookbook.
        /// </summary>
        public static string EditCookBook {
            get {
                return ResourceManager.GetString("EditCookBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keto.
        /// </summary>
        public static string KetoDietName {
            get {
                return ResourceManager.GetString("KetoDietName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen Knowledge.
        /// </summary>
        public static string KitchenKnowledgeName {
            get {
                return ResourceManager.GetString("KitchenKnowledgeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        public static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchandise Knowledge.
        /// </summary>
        public static string MerchandiseKnowledgeName {
            get {
                return ResourceManager.GetString("MerchandiseKnowledgeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open another Cookbook.
        /// </summary>
        public static string OpenAnotherCookBook {
            get {
                return ResourceManager.GetString("OpenAnotherCookBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsName {
            get {
                return ResourceManager.GetString("OptionsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        public static string RecipesName {
            get {
                return ResourceManager.GetString("RecipesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Book.
        /// </summary>
        public static string SelectedBook {
            get {
                return ResourceManager.GetString("SelectedBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegan.
        /// </summary>
        public static string VeganDietName {
            get {
                return ResourceManager.GetString("VeganDietName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetarien.
        /// </summary>
        public static string VegetarienDietName {
            get {
                return ResourceManager.GetString("VegetarienDietName", resourceCulture);
            }
        }
    }
}
